ALTER TABLE "Note" ADD COLUMN "type" TEXT NOT NULL DEFAULT 'note';
ALTER TABLE "Note" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Note" ADD COLUMN "dueDate" DATETIME;
ALTER TABLE "Note" ADD COLUMN "completed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Note" ADD COLUMN "latitude" REAL;
ALTER TABLE "Note" ADD COLUMN "longitude" REAL;
ALTER TABLE "Note" ADD COLUMN "location" TEXT;